export const colors = {
  background: '#F6F8FB',
  backgroundAlt: '#EDF3FA',
  surface: '#FFFFFF',
  surfaceMuted: '#EEF5FF',
  surfaceSoft: '#F9FBFF',
  primary: '#8CB8FF',
  primarySoft: '#DCEAFF',
  primaryDeep: '#2F5EA8',
  primaryText: '#244A84',
  accentMint: '#DDF4EC',
  accentGold: '#FFF2D8',
  textPrimary: '#132238',
  textSecondary: '#55657D',
  textTertiary: '#8B98AB',
  border: '#D8E4F2',
  divider: '#E6EDF5',
  success: '#2C8C67',
  error: '#C85A5A',
  warning: '#C48A2C',
  shadow: '#10233D',
} as const;
